
package lucot_jlist_cmbobox;

import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;


public class MainFrame extends javax.swing.JFrame {

    static DefaultListModel<String> malePremieremodel;
     static DefaultListModel<String> maleDeluxemodel;
     static DefaultListModel<String> femalePremieremodel;
     static DefaultListModel<String> femaleDeluxemodel;
     
    public MainFrame() {
        initComponents();
        malePremieremodel = new DefaultListModel<>();
        femalePremieremodel = new DefaultListModel<>();
        maleDeluxemodel = new DefaultListModel<>();
        femaleDeluxemodel = new DefaultListModel<>();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public String properCase(String name){
        String pc = "";
        for(String value: name.split(" ")){
            pc += value.toUpperCase().charAt(0)+value.substring(1)+" ";
        }
        return pc;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roomtype = new javax.swing.JComboBox<>();
        addbutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        genderCmboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        malePremiereList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        MPDeleteButton = new javax.swing.JButton();
        MalePremiereClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        femalePremiereList = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        FPDeleteButton = new javax.swing.JButton();
        FemalePremiereClear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        maleDeluxeList = new javax.swing.JList<>();
        MDDeleteButton = new javax.swing.JButton();
        MaleDeluxeClear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        femaleDeluxeList = new javax.swing.JList<>();
        FemaleDeluxeClear = new javax.swing.JButton();
        FDDeleteButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(799, 566));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Information:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lastname:");

        fname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Firstname:");

        lname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnameFocusGained(evt);
            }
        });
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RoomType:");

        roomtype.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLEASE SELECT", "PREMIERE", "DELUXE" }));
        roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtypeActionPerformed(evt);
            }
        });

        addbutton.setBackground(new java.awt.Color(102, 153, 255));
        addbutton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        editbutton.setBackground(new java.awt.Color(102, 153, 255));
        editbutton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editbutton.setForeground(new java.awt.Color(255, 255, 255));
        editbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        editbutton.setText("EDIT");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        String[] genders = {"PLEASE SELECT","MALE","FEMALE"};

        DefaultComboBoxModel<String>model = new DefaultComboBoxModel<>(genders);
        genderCmboBox.setModel(model);
        genderCmboBox.setRenderer(new DefaultListCellRenderer(){
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus){
                JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if(value.equals("MALE")) {
                    Icon maleIcon = new ImageIcon(getClass().getResource("male.png"));
                    label.setIcon(maleIcon);
                }       else if (value.equals("FEMALE")) {
                    Icon femaleIcon = new ImageIcon(getClass().getResource("female.png"));
                    label.setIcon(femaleIcon);
                }
                return label;
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editbutton))
                            .addComponent(lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(genderCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(genderCmboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(editbutton))
                .addGap(154, 154, 154))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("PREMIERE");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 77, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        malePremiereList.setBackground(new java.awt.Color(153, 204, 255));
        malePremiereList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        malePremiereList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malePremiereListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(malePremiereList);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 30, 286, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lucot_jlist_cmbobox/male.png"))); // NOI18N
        jLabel7.setText("MALE");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 79, -1));

        MPDeleteButton.setBackground(new java.awt.Color(255, 0, 51));
        MPDeleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MPDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        MPDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        MPDeleteButton.setText("DELETE USER");
        MPDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPDeleteButtonActionPerformed(evt);
            }
        });
        jPanel3.add(MPDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 172, -1, -1));

        MalePremiereClear.setBackground(new java.awt.Color(102, 0, 51));
        MalePremiereClear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MalePremiereClear.setForeground(new java.awt.Color(255, 255, 255));
        MalePremiereClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        MalePremiereClear.setText("CLEARLIST");
        MalePremiereClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalePremiereClearActionPerformed(evt);
            }
        });
        jPanel3.add(MalePremiereClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 172, -1, -1));

        femalePremiereList.setBackground(new java.awt.Color(255, 204, 204));
        femalePremiereList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        femalePremiereList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femalePremiereListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(femalePremiereList);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 258, 286, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lucot_jlist_cmbobox/female.png"))); // NOI18N
        jLabel8.setText("FEMALE");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        FPDeleteButton.setBackground(new java.awt.Color(255, 0, 51));
        FPDeleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FPDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        FPDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        FPDeleteButton.setText("DELETE USER");
        FPDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPDeleteButtonActionPerformed(evt);
            }
        });
        jPanel3.add(FPDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 400, -1, -1));

        FemalePremiereClear.setBackground(new java.awt.Color(102, 0, 51));
        FemalePremiereClear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FemalePremiereClear.setForeground(new java.awt.Color(255, 255, 255));
        FemalePremiereClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        FemalePremiereClear.setText("CLEARLIST");
        FemalePremiereClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemalePremiereClearActionPerformed(evt);
            }
        });
        jPanel3.add(FemalePremiereClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 400, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, 300, 530));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 51, 204));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("DELUXE");
        jLabel9.setOpaque(true);
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 537));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lucot_jlist_cmbobox/male.png"))); // NOI18N
        jLabel10.setText("MALE");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        maleDeluxeList.setBackground(new java.awt.Color(153, 204, 255));
        maleDeluxeList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        maleDeluxeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleDeluxeListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(maleDeluxeList);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 33, 280, 131));

        MDDeleteButton.setBackground(new java.awt.Color(255, 0, 51));
        MDDeleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MDDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        MDDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        MDDeleteButton.setText("DELETE USER");
        MDDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDDeleteButtonActionPerformed(evt);
            }
        });
        jPanel5.add(MDDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 170, -1, -1));

        MaleDeluxeClear.setBackground(new java.awt.Color(102, 0, 51));
        MaleDeluxeClear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaleDeluxeClear.setForeground(new java.awt.Color(255, 255, 255));
        MaleDeluxeClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        MaleDeluxeClear.setText("CLEARLIST");
        MaleDeluxeClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleDeluxeClearActionPerformed(evt);
            }
        });
        jPanel5.add(MaleDeluxeClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 170, -1, -1));

        femaleDeluxeList.setBackground(new java.awt.Color(255, 204, 204));
        femaleDeluxeList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        femaleDeluxeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleDeluxeListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(femaleDeluxeList);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 259, 280, 131));

        FemaleDeluxeClear.setBackground(new java.awt.Color(102, 0, 51));
        FemaleDeluxeClear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FemaleDeluxeClear.setForeground(new java.awt.Color(255, 255, 255));
        FemaleDeluxeClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        FemaleDeluxeClear.setText("CLEARLIST");
        FemaleDeluxeClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleDeluxeClearActionPerformed(evt);
            }
        });
        jPanel5.add(FemaleDeluxeClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        FDDeleteButton.setBackground(new java.awt.Color(255, 0, 51));
        FDDeleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FDDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        FDDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        FDDeleteButton.setText("DELETE USER");
        FDDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDDeleteButtonActionPerformed(evt);
            }
        });
        jPanel5.add(FDDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lucot_jlist_cmbobox/female.png"))); // NOI18N
        jLabel11.setText("FEMALE");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, -1, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // ADD BUTTON FUNCTION
        String fnametxt = fname.getText();
        String lnametxt = lname.getText();
        if(fname.getText().isEmpty() || !fname.getText().matches("[ a-zA-Z]+")){
            JOptionPane.showMessageDialog(rootPane, "Invalid Input!\nPlease Enter A Proper First Name.", null, HEIGHT);
            return;
        }
        if(lname.getText().isEmpty() || !lname.getText().matches("[ a-zA-Z]+")){
            JOptionPane.showMessageDialog(rootPane, "Invalid Input!\nPlease Enter A Proper Last Name.", null, HEIGHT);
            return;
        }
        if(genderCmboBox.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "please select in gender.", null, HEIGHT);
            return;
        }
        if(roomtype.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "please select a roomtype.", null, HEIGHT);
            return;
        }
        
        if(genderCmboBox.getSelectedItem().equals("MALE") && roomtype.getSelectedItem().equals("PREMIERE")){
        malePremieremodel.addElement(properCase(lnametxt)+", "+properCase(fnametxt));
        malePremiereList.setModel(malePremieremodel);
        }
        
        if(genderCmboBox.getSelectedItem().equals("FEMALE")&& roomtype.getSelectedItem().equals("PREMIERE")){
        femalePremieremodel.addElement(properCase(lnametxt)+", "+properCase(fnametxt));
        femalePremiereList.setModel(femalePremieremodel);
        }
        
        if(genderCmboBox.getSelectedItem().equals("MALE") && roomtype.getSelectedItem().equals("DELUXE")){
        maleDeluxemodel.addElement(properCase(lnametxt)+", "+properCase(fnametxt));
        maleDeluxeList.setModel(maleDeluxemodel);
        }
        if(genderCmboBox.getSelectedItem().equals("FEMALE")&& roomtype.getSelectedItem().equals("DELUXE")){
        femaleDeluxemodel.addElement(properCase(lnametxt)+", "+properCase(fnametxt));
        femaleDeluxeList.setModel(femaleDeluxemodel);
        }
        fname.setText("");
        lname.setText("");
        genderCmboBox.setSelectedIndex(0);
        roomtype.setSelectedIndex(0);
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fnameActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // EDIT BUTTON FUNCTION
        if(editbutton.getText().equals("EDIT")){
            editbutton.setText("UPDATE");
            genderCmboBox.setEnabled(false);
            roomtype.setEnabled(false);
            if(malePremiereList.getSelectedIndex() > -1){
            String MPgetName = malePremiereList.getSelectedValue();
            String[] name = MPgetName.split(", ");
            String getFname = name[1];
            String getLname = name[0];
            fname.setText(getFname);
            lname.setText(getLname);
            }
            else if(femalePremiereList.getSelectedIndex() > -1){
            String FPgetName = femalePremiereList.getSelectedValue();
            String[] name = FPgetName.split(", ");
            String getFname = name[1];
            String getLname = name[0];
            fname.setText(getFname);
            lname.setText(getLname);
            }
            else if(maleDeluxeList.getSelectedIndex() > -1){
            String MDgetName = maleDeluxeList.getSelectedValue();
            String[] name = MDgetName.split(", ");
            String getFname = name[1];
            String getLname = name[0];
            fname.setText(getFname);
            lname.setText(getLname);
            }
            else if(femaleDeluxeList.getSelectedIndex() > -1){
            String FDgetName = femaleDeluxeList.getSelectedValue();
            String[] name = FDgetName.split(", ");
            String getFname = name[1];
            String getLname = name[0];
            fname.setText(getFname);
            lname.setText(getLname);
            }
        }                                                                                                                                                                                                                     
        else{
            editbutton.setText("EDIT");
            genderCmboBox.setEnabled(true);
            roomtype.setEnabled(true);
            if(malePremiereList.getSelectedIndex() > -1){
            int MPindex = malePremiereList.getSelectedIndex();
            malePremieremodel.setElementAt(properCase(lname.getText())+", "+properCase(fname.getText()), MPindex);
            editbutton.setEnabled(false);
            MPDeleteButton.setEnabled(false);
            addbutton.setEnabled(true);
            fname.setText(null);
            lname.setText(null);
            malePremiereList.setEnabled(true);
            }
            
            if(femalePremiereList.getSelectedIndex() > -1){
            int FPindex = femalePremiereList.getSelectedIndex();
            femalePremieremodel.setElementAt(properCase(lname.getText())+", "+properCase(fname.getText()), FPindex);
            editbutton.setEnabled(false);
            FPDeleteButton.setEnabled(false);
            addbutton.setEnabled(true);
            fname.setText(null);
            lname.setText(null);
            femalePremiereList.setEnabled(true);
            }
            
            if(maleDeluxeList.getSelectedIndex() > -1){
            int MDindex = maleDeluxeList.getSelectedIndex();
            maleDeluxemodel.setElementAt(properCase(lname.getText())+", "+properCase(fname.getText()), MDindex);
            editbutton.setEnabled(false);
            MDDeleteButton.setEnabled(false);
            addbutton.setEnabled(true);
            fname.setText(null);
            lname.setText(null);
            maleDeluxeList.setEnabled(true);
            }
            
            if(femaleDeluxeList.getSelectedIndex() > -1){
            int FDindex = femaleDeluxeList.getSelectedIndex();
            femaleDeluxemodel.setElementAt(properCase(lname.getText())+", "+properCase(fname.getText()), FDindex);
            editbutton.setEnabled(false);
            FDDeleteButton.setEnabled(false);
            addbutton.setEnabled(true);
            fname.setText(null);
            lname.setText(null);
            femaleDeluxeList.setEnabled(true);
            }
            JOptionPane.showMessageDialog(rootPane, "User Updated",null,JOptionPane.INFORMATION_MESSAGE);
            malePremiereList.clearSelection();
            femalePremiereList.clearSelection();
            maleDeluxeList.clearSelection();
            femaleDeluxeList.clearSelection();
        }
    }//GEN-LAST:event_editbuttonActionPerformed

    private void malePremiereListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malePremiereListMouseClicked
        // male premiere list mouse clicked
        if(malePremiereList.getSelectedIndex() > -1){
            editbutton.setEnabled(true);
            MPDeleteButton.setEnabled(true);
            addbutton.setEnabled(false);
        }
    }//GEN-LAST:event_malePremiereListMouseClicked

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        if(editbutton.getText().equals("UPDATE")){
            addbutton.setEnabled(false);
            MPDeleteButton.setEnabled(false);
            FPDeleteButton.setEnabled(false);
            MDDeleteButton.setEnabled(false);
            FDDeleteButton.setEnabled(false);
        }
        else{
            addbutton.setEnabled(true);
            MPDeleteButton.setEnabled(false);
            FPDeleteButton.setEnabled(false);
            MDDeleteButton.setEnabled(false);
            FDDeleteButton.setEnabled(false);
            editbutton.setEnabled(false);
        }
    }//GEN-LAST:event_fnameFocusGained

    private void lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusGained
         if(editbutton.getText().equals("UPDATE")){
            addbutton.setEnabled(false);
            MPDeleteButton.setEnabled(false);
            FPDeleteButton.setEnabled(false);
            MDDeleteButton.setEnabled(false);
            FDDeleteButton.setEnabled(false);
        }
        else{
            addbutton.setEnabled(true);
            MPDeleteButton.setEnabled(false);
            FPDeleteButton.setEnabled(false);
            MDDeleteButton.setEnabled(false);
            FDDeleteButton.setEnabled(false);
            editbutton.setEnabled(false);
        }
    }//GEN-LAST:event_lnameFocusGained

    private void FemaleDeluxeClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleDeluxeClearActionPerformed
        // FEMALE DELUXE BUTTON CLEARLIST
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to clear this list?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
        femaleDeluxemodel.removeAllElements();
        }
        
    }//GEN-LAST:event_FemaleDeluxeClearActionPerformed

    private void FDDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDDeleteButtonActionPerformed
        // FEMALE DELUXE DELETE BUTTON FUNCTION
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete this user?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
           String selectedItem = femaleDeluxeList.getSelectedValue();
           femaleDeluxemodel.removeElement(selectedItem);
        }
        
    }//GEN-LAST:event_FDDeleteButtonActionPerformed

    private void MaleDeluxeClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleDeluxeClearActionPerformed
        // MALE DELUXE CLEARLIST BUTTON FUNCTION
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to clear this list?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
        maleDeluxemodel.removeAllElements();
        }
        
    }//GEN-LAST:event_MaleDeluxeClearActionPerformed

    private void MDDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDDeleteButtonActionPerformed
        // MALE DELUXE BUTTON FUNCTION
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete this user?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
           String selectedItem = maleDeluxeList.getSelectedValue();
           maleDeluxemodel.removeElement(selectedItem);
        }
        
    }//GEN-LAST:event_MDDeleteButtonActionPerformed

    private void FemalePremiereClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemalePremiereClearActionPerformed
        // FEMALE PREMIERE BUTTON CLEARLIST FUNCTION
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to clear this list?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
        femalePremieremodel.removeAllElements();
        }
        
    }//GEN-LAST:event_FemalePremiereClearActionPerformed

    private void FPDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPDeleteButtonActionPerformed
        // FEMALE PREMIERE DELETE BUTTON FUNCTION
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete this user?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
           String selectedItem = femalePremiereList.getSelectedValue();
           femalePremieremodel.removeElement(selectedItem);
        }
        
    }//GEN-LAST:event_FPDeleteButtonActionPerformed

    private void MalePremiereClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalePremiereClearActionPerformed
        // MALE PREMIERE CLEARLIST BUTTON FUNCTION
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to clear this list?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
        malePremieremodel.removeAllElements();
        }
        
    }//GEN-LAST:event_MalePremiereClearActionPerformed

    private void MPDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPDeleteButtonActionPerformed
        // MALE PREMIERE DELETE BUTTON FUNCTION
        int result = JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete this user?", null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
           String selectedItem = malePremiereList.getSelectedValue();
            malePremieremodel.removeElement(selectedItem);
        }

    }//GEN-LAST:event_MPDeleteButtonActionPerformed

    private void femalePremiereListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femalePremiereListMouseClicked
        // female premiere mouse clicked method
        if(femalePremiereList.getSelectedIndex() > -1){
            editbutton.setEnabled(true);
            FPDeleteButton.setEnabled(true);
            addbutton.setEnabled(false);
        }
    }//GEN-LAST:event_femalePremiereListMouseClicked

    private void maleDeluxeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleDeluxeListMouseClicked
        // Male deluxe mouse clicked method
        if(maleDeluxeList.getSelectedIndex() > -1){
            editbutton.setEnabled(true);
            MDDeleteButton.setEnabled(true);
            addbutton.setEnabled(false);
        }
    }//GEN-LAST:event_maleDeluxeListMouseClicked

    private void femaleDeluxeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleDeluxeListMouseClicked
        // Female Deluxe List Mouse Clicked
         if(femaleDeluxeList.getSelectedIndex() > -1){
            editbutton.setEnabled(true);
            FDDeleteButton.setEnabled(true);
            addbutton.setEnabled(false);
        }
    }//GEN-LAST:event_femaleDeluxeListMouseClicked

    private void roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomtypeActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FDDeleteButton;
    private javax.swing.JButton FPDeleteButton;
    private javax.swing.JButton FemaleDeluxeClear;
    private javax.swing.JButton FemalePremiereClear;
    private javax.swing.JButton MDDeleteButton;
    private javax.swing.JButton MPDeleteButton;
    private javax.swing.JButton MaleDeluxeClear;
    private javax.swing.JButton MalePremiereClear;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton editbutton;
    private javax.swing.JList<String> femaleDeluxeList;
    private javax.swing.JList<String> femalePremiereList;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> genderCmboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lname;
    private javax.swing.JList<String> maleDeluxeList;
    private javax.swing.JList<String> malePremiereList;
    private javax.swing.JComboBox<String> roomtype;
    // End of variables declaration//GEN-END:variables
}
